export const FETCH_GAME_SETTINGS_REQUEST = 'game-field/FETCH_GAME_SETTINGS_REQUEST';
export const FETCH_GAME_SETTINGS_SUCCESS = 'game-field/FETCH_GAME_SETTINGS_SUCCESS';
export const FETCH_GAME_SETTINGS_FAILED = 'game-field/FETCH_GAME_SETTINGS_FAILED';
