export const FETCH_WINNERS_REQUEST = 'winners/FETCH_WINNERS_REQUEST';
export const FETCH_WINNERS_SUCCESS = 'winners/FETCH_WINNERS_SUCCESS';
export const FETCH_WINNERS_FAILED = 'winners/FETCH_WINNERS_FAILED';
