export const FETCH_WINNERS_REQUEST = 'winners/FETCH_WINNERS_REQUEST';
export const FETCH_WINNERS_SUCCESS = 'winners/FETCH_WINNERS_SUCCESS';
export const FETCH_WINNERS_FAILED = 'winners/FETCH_WINNERS_FAILED';

export const SEND_WINNER_REQUEST = 'winners/SEND_WINNER_REQUEST';
export const SEND_WINNER_SUCCESS = 'winners/SEND_WINNER_SUCCESS';
export const SEND_WINNER_FAILED = 'winners/SEND_WINNER_FAILED';
